export const conversations = [
  {
    id: Math.random(),
    title: "FX Accounting Revaluation",
    icon: "fa-2x fas fa-robot",
    createdAt: "Apr 16",
    messages: [
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "hey man",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "",
        message: "whats going on bro?",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "nothing much just chilling",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
    ],
  },
  {
    id: Math.random(),
    title: "Contra Cogs",
    icon: "fa-2x fas fa-robot",
    createdAt: "Apr 16",
    messages: [
      {
        messageID: Math.random(),
        userID: "",
        message: "already",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "alright bro",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "",
        message: "alright hit you up later",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
    ],
  },
  {
    id: Math.random(),
    title: "Transportation",
    icon: "fa-2x fas fa-robot",
    createdAt: "Apr 16",
    messages: [
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "hey man",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "",
        message: "whats going on bro?",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "nothing much just chilling",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "",
        message: "already",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "alright bro",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "",
        message: "alright hit you up later",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
    ],
  },
  {
    id: Math.random(),
    title: "SVOD",
    icon: "fa-2x fas fa-file-excel",
    createdAt: "Apr 16",
    messages: [
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "alright bro",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
      {
        messageID: Math.random(),
        userID: "",
        message: "alright hit you up later",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
    ],
  },
  {
    id: Math.random(),
    title: "OCM",
    icon: "fa-2x fas fa-file-excel",
    createdAt: "Apr 16",
    messages: [
      {
        messageID: Math.random(),
        userID: "tyiska",
        message: "hey man",
        icon: "fa-2x fas fa-robot",
        createdAt: "Apr 16",
      },
    ],
  },
];
